repos:
  - repo: https://github.com/mineiros-io/pre-commit-hooks
    rev: v0.5.1
    hooks:
      - id: terraform-fmt
        exclude: "^stuff.*$"
      - id: terraform-fmt
      - id: terramate-generate
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.17.0"
    hooks:
      - id: terraform-docs-go
        args: ["--output-file", "README.md","--recursive"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Yaml and Json
      - id: check-yaml
      - id: pretty-format-json
        args: [ --autofix ]
        exclude: ^.*bats-tests.*\.json$
      - id: sort-simple-yaml

      # Git style57377180
      - id: check-added-large-files
        exclude: "^.*vsdx$"
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-new-submodules

      # Common errors
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
        exclude: CHANGELOG.md
      - id: check-executables-have-shebangs

      # Cross platform
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [ --fix=lf ]
      - id: detect-private-key

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '3.2.83'
    hooks:
      - id: checkov
        args:
        - --skip-check=CKV_TF_1 # Ensure Terraform module sources use a commit hashCKV_TF_1
        - --download-external-modules=true
        - --config-file=.checkov.yaml
        - --quiet

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: shellcheck
      - id: gofmt
      - id: golint

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
        -   --max-line-length=120
        -   --ignore=E203,E501,W503
